CREATE TABLE IF NOT EXISTS processed_weather_data (
    id SERIAL PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    event_timestamp TIMESTAMP NOT NULL,
    processing_timestamp TIMESTAMP NOT NULL,
    data_lag INTERVAL NOT NULL,
    temperature DECIMAL(5,2) NOT NULL,
    temperature_fahrenheit DECIMAL(5,2) NOT NULL,
    feels_like DECIMAL(5,2) NOT NULL,
    humidity INTEGER NOT NULL,
    pressure INTEGER NOT NULL,
    wind_speed DECIMAL(5,2) NOT NULL,
    wind_speed_mph DECIMAL(5,2) NOT NULL,
    description VARCHAR(200) NOT NULL,
    temp_category VARCHAR(50) NOT NULL,
    is_daytime BOOLEAN NOT NULL,
    weather_severity DECIMAL(5,2) NOT NULL,
    hour INTEGER NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT temp_range CHECK (temperature BETWEEN -100 AND 100),
    CONSTRAINT humidity_range CHECK (humidity BETWEEN 0 AND 100),
    CONSTRAINT hour_range CHECK (hour BETWEEN 0 AND 23)
);
